import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../shared/prototypeExtension/date'
import {Navbar} from '@/components/ui/header/navbar';
import {PropsWithChildren} from 'react';

const inter = Inter({ subsets: ['latin'] });

declare global {
  interface Date {
    /**
     * Returns a string representation of the date formatted according to the specified format.
     *
     * Formatters are :
     *
     *  - Y for the full year ex : 2023
     *  - y for the short year syntax ex : 23
     *  - m for the month in integer ex : 03
     *  - M for the 3 first letter of the month ex : Avr
     *  - d for the day number ex : 21
     *  - D for the 3 first letter of the day ex : Lun
     *  - N for the day number in the week ex : 1 for monday, 7 for sunday
     *  - H for the hours
     *  - i for the minutes
     */
    formatDate: (format: string) => string;
    addDay: (numberOfDay: number) => Date;
    normalizeTimeZone: () => Date;
    startOfWeek: () => Date;
    endOfWeek: () => Date;
    getDayName: () => 'Lundi'|'Mardi'|'Mercredi'|'Jeudi'|'Vendredi'|'Samedi'|'Dimanche';
    addMonth: (numberOfMonth: number) => Date;
    addYear: (numberOfYear: number) => Date;

  }
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({children}: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-bg-primary flex flex-col min-h-screen`}>
        <header className="sticky top-0">
          <Navbar />
        </header>
        <main className="flex flex-grow flex-col items-center py-5 sm:py-10 max-w-7xl px-5 sm:px-6 lg:px-8">
          {children}
        </main>
        <footer className="w-full h-56 bg-background-secondary">

        </footer>
      </body>
    </html>
  )
}
